/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as PropertiesNewRouteImport } from './routes/properties.new'
import { Route as ClientsClientIdEditRouteImport } from './routes/clients.$clientId.edit'
import { Route as PropertiesPropertyIdEditRouteImport } from './routes/properties.$propertyId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdEditRoute = ClientsClientIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ClientsClientIdRoute,
} as any)
const PropertiesPropertyIdEditRoute =
  PropertiesPropertyIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => PropertiesPropertyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/followups': typeof FollowupsRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRouteWithChildren
  '/properties/new': typeof PropertiesNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/clients/$clientId/edit': typeof ClientsClientIdEditRoute
  '/properties/$propertyId/edit': typeof PropertiesPropertyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/followups': typeof FollowupsRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRouteWithChildren
  '/properties/new': typeof PropertiesNewRoute
  '/clients': typeof ClientsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/clients/$clientId/edit': typeof ClientsClientIdEditRoute
  '/properties/$propertyId/edit': typeof PropertiesPropertyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/followups': typeof FollowupsRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRouteWithChildren
  '/properties/new': typeof PropertiesNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/clients/$clientId/edit': typeof ClientsClientIdEditRoute
  '/properties/$propertyId/edit': typeof PropertiesPropertyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/followups'
    | '/settings'
    | '/welcome'
    | '/clients/$clientId'
    | '/clients/new'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/clients/'
    | '/properties/'
    | '/clients/$clientId/edit'
    | '/properties/$propertyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/followups'
    | '/settings'
    | '/welcome'
    | '/clients/$clientId'
    | '/clients/new'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/clients'
    | '/properties'
    | '/clients/$clientId/edit'
    | '/properties/$propertyId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/followups'
    | '/settings'
    | '/welcome'
    | '/clients/$clientId'
    | '/clients/new'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/clients/'
    | '/properties/'
    | '/clients/$clientId/edit'
    | '/properties/$propertyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FollowupsRoute: typeof FollowupsRoute
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRouteWithChildren
  PropertiesNewRoute: typeof PropertiesNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/new': {
      id: '/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId/edit': {
      id: '/clients/$clientId/edit'
      path: '/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof ClientsClientIdEditRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/properties/$propertyId/edit': {
      id: '/properties/$propertyId/edit'
      path: '/edit'
      fullPath: '/properties/$propertyId/edit'
      preLoaderRoute: typeof PropertiesPropertyIdEditRouteImport
      parentRoute: typeof PropertiesPropertyIdRoute
    }
  }
}

interface ClientsClientIdRouteChildren {
  ClientsClientIdEditRoute: typeof ClientsClientIdEditRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdEditRoute: ClientsClientIdEditRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

interface PropertiesPropertyIdRouteChildren {
  PropertiesPropertyIdEditRoute: typeof PropertiesPropertyIdEditRoute
}

const PropertiesPropertyIdRouteChildren: PropertiesPropertyIdRouteChildren = {
  PropertiesPropertyIdEditRoute: PropertiesPropertyIdEditRoute,
}

const PropertiesPropertyIdRouteWithChildren =
  PropertiesPropertyIdRoute._addFileChildren(PropertiesPropertyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FollowupsRoute: FollowupsRoute,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRouteWithChildren,
  PropertiesNewRoute: PropertiesNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
